apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-smr
  labels:
    app: k8s-smr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-smr
  template:
    metadata:
      labels:
        app: k8s-smr
    spec:
      initContainers:
        - name: {{ .Values.proxySetup.name }}
          image: {{ .Values.proxySetup.image }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.service.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
        - name: {{ .Values.server.name }}
          image: {{ .Values.server.image }}
          ports:
            - containerPort: {{ .Values.server.port }}
          env:
            - name: PROXY_PORT
              value: {{ .Values.server.port | quote }}
            - name: SERVICE_PORT
              value: {{ .Values.service.port | quote }}